Issues Fix
Runbhumi/Runbhumi pull request #329
Opened 2021-02-09 15:57 UTC by Manas1820

# Description

Please include the summary of the change as well as the issue that is fixed (if applicable). Also if any dependencies that are required for this change to work.

Fixes #322 

## Type of change

Please choose the relavant type of change.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Also summarise the process for us to reproduce.

- [ ] Test A: checked through my emulator.
- [ ] Test B: Firebase testing labs
- [ ] Test C: Test through flutter test code
- [ ] Test D: Other (Please specify)

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this application
- [ ] I have checked the code working on my emulator
- [ ] I have commented my code for better understanding
- [ ] These changes generate no new warnings
- [ ] These changes do not effect the existing functionalities,

2021-02-09 16:06 UTC, hayat-tamboli requested changes
Bro change the license content too

2021-02-09 17:58 UTC, Manas1820 commented
> Bro change the license content too

done

2021-02-09 20:45 UTC, hayat-tamboli requested changes
please revert the websiteURL to "https://runbhumi-website.vercel.app/" in line 209 of lib/view/profile/drawer/drawer.dart

2021-02-09 20:45 UTC, hayat-tamboli commented on lib/view/profile/drawer/drawer.dart
> +var websiteURL = "https://runbhumi-website.vercel.app/feedback";
bro revert this back

2021-02-10 07:11 UTC, Manas1820 commented
> please revert the websiteURL to "https://runbhumi-website.vercel.app/" in line 209 of lib/view/profile/drawer/drawer.dart

ok

2021-02-10 16:14 UTC, hayat-tamboli approved these changes

2021-02-10 16:14 UTC, merged